blueprint:
  name: Multi-Switch Synchronization
  description: Synchronize multiple switches with a light, switch, or fan. When any device changes state, all others will match.
  domain: automation
  input:
    target_device:
      name: Target Device
      description: The main device to synchronize (light, switch, or fan)
      selector:
        entity:
          domain:
            - light
            - switch
            - fan
    
    sync_switches:
      name: Switches to Sync
      description: One or more switches that should stay synchronized with the target device
      selector:
        entity:
          domain: switch
          multiple: true

mode: single

triggers:
  # Trigger when target device changes state
  - platform: state
    entity_id: !input target_device
    id: target_device
  
  # Trigger when any sync switch changes state
  - platform: state
    entity_id: !input sync_switches
    id: sync_switch

actions:
  - choose:
      # When target device changes, update all switches
      - conditions:
          - condition: trigger
            id: target_device
        sequence:
          - if:
              - condition: state
                entity_id: !input target_device
                state: "on"
            then:
              - action: switch.turn_on
                target:
                  entity_id: !input sync_switches
            else:
              - action: switch.turn_off
                target:
                  entity_id: !input sync_switches
      
      # When a sync switch changes, update target device
      - conditions:
          - condition: trigger
            id: sync_switch
        sequence:
          - if:
              - condition: state
                entity_id: "{{ trigger.entity_id }}"
                state: "on"
            then:
              - action: homeassistant.turn_on
                target:
                  entity_id: !input target_device
            else:
              - action: homeassistant.turn_off
                target:
                  entity_id: !input target_device
