blueprint:
  name: Switch Controlled Cover with State Sync
  description: Controls a cover (blinds/shades) with a switch while maintaining state synchronization between them.
  domain: automation
  source_url: https://github.com/bradyemerson/homeassistant/blob/main/blueprints/automation/switch-controlled-cover-with-sync.yaml
  input:
    switch_entity:
      name: Control Switch
      description: The switch that will control the cover
      selector:
        entity:
          domain: switch
    cover_entity:
      name: Shades/Blinds
      description: The shades/blinds to be controlled
      selector:
        entity:
          domain: cover

mode: restart
variables:
  cover_entity_var: !input "cover_entity"

triggers:
  # Trigger on switch changes
  - trigger: state
    entity_id: !input switch_entity
    id: button-state-change
  # Trigger on blind state changes
  - trigger: state
    entity_id: !input cover_entity
    id: blinds-state-change
    from: null
    to: null
  # Trigger on HA startup
  - trigger: homeassistant
    event: start
    id: hass-start-up

action:
  - choose:
      # Handle switch state changes
      - conditions:
          - condition: trigger
            id:
              - button-state-change
        sequence:
          - target:
              entity_id: !input cover_entity
            action: |-
              {% if trigger.to_state.state == 'on' %}
                cover.open_cover
              {% else %}
                cover.close_cover
              {% endif %}
      
      # Handle blind state changes and HA startup
      - conditions:
          - condition: trigger
            id:
              - hass-start-up
              - blinds-state-change
        sequence:
          - target:
              entity_id: !input switch_entity
            action: |-
              {% if states(cover_entity_var) == 'open' %}
                switch.turn_on
              {% elif states(cover_entity_var) == 'closed' %}
                switch.turn_off
              {% endif %}
 
